version: '2'

services:

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
      - 2888:2888
      - 3888:3888
    env_file:
      - ./zookeeper/zookeeper.env 
    hostname:
        zookeeper
    networks:
        default:
            aliases:
                - zookeeper 

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 173.34.0.0/16
    
volumes:
  db-data:
    driver: local